### ISSUE TITLE
Run your site on HHVM

### ISSUE THREAD

**Issue by ptarjan** [h4cc/hhvm-progress#20]
I see `X-Powered-By:	PHP/5.3.10-1ubuntu3.9`. :)

**Comment by h4cc** [comment]
![](http://i19.photobucket.com/albums/b176/ellencat321/Sims/Lj/FarnsworthGoodNews_zpsb5a378dd.png)

I have worked at a HHVM and partial Hack branch that will be ready in some time for production use :)

**Comment by ptarjan** [comment]
:smiley:

**Comment by h4cc** [comment]
Did it! http://hhvm.h4cc.de/

`Running on PHP Version: 5.6.99-hhvm`

**Comment by ptarjan** [comment]
yay! The green is getting bigger too.
