### ISSUE TITLE
Package is misidentified as "Not a PHP library" 

### ISSUE THREAD

**Issue by s9e** [h4cc/hhvm-progress#42]
[hhvm.h4cc.de status](http://hhvm.h4cc.de/package/s9e/text-formatter)
[Package's .travis.yml](https://github.com/s9e/TextFormatter/blob/master/.travis.yml)
[Package's composer.json](https://github.com/s9e/TextFormatter/blob/master/composer.json)

The test suite passes with flying colors [on Travis](https://travis-ci.org/s9e/TextFormatter) and the composer.json file declares the package as a library. HHVM is enabled in .travis.yml in matrix->include->php rather than in the php key directly, could that be the problem here? I use matrix->include to control the order in which the builds are executed.

**Comment by h4cc** [comment]
`dev-master` is now recognized as a PHP Build :fireworks: 

The other branches can not be parsed, because they do not contain a `.travis.yml` file, as you might know.

**Comment by s9e** [comment]
Awesome, thanks.
