### ISSUE TITLE
Package has wrong status

### ISSUE THREAD

**Issue by h4cc** [h4cc/hhvm-progress#46]
https://twitter.com/elfchat/status/548214899290439681

**Comment by stof** [comment]
If you look at the graph on http://hhvm.h4cc.de/graphs/symfony_2_6.png, many packages are missing their tested status (symfony/symfony is partially tested, symfony/monolog-bundle is fully tested, etc.

but it may be related to #45

**Comment by h4cc** [comment]
Seems to be fixed.
