### ISSUE TITLE
PNG badge urls are returning a 404

### ISSUE THREAD

**Issue by stof** [h4cc/hhvm-progress#53]
This is breaking badges in readmes of all projects using the badges, which is a bad idea. Providing a SVG badge is good, but existing URLs should remain functional

**Comment by h4cc** [comment]
Which package badge does return 404?

The PNG feature itself is still working: http://hhvm.h4cc.de/badge/symfony/symfony.png

**Comment by stof** [comment]
http://hhvm.h4cc.de/badge/behat/behat.png?branch=master is a 404

**Comment by stof** [comment]
hmm, looks like the issue is actually that the handling of branch names changed by expecting a composer version rather than a branch name

**Comment by h4cc** [comment]
Ah, i see. This URL works: http://hhvm.h4cc.de/badge/behat/behat.png?branch=dev-master

I will try to accept both or fix it as far as possible.

**Comment by h4cc** [comment]
Badges work now. Thank you very much for your contribution! :+1:
