### ISSUE TITLE
Confusing explanation about refreshing the page

### ISSUE THREAD

**Issue by stof** [h4cc/hhvm-progress#56]
The bottom of the page has a message explaining how to refresh:
![hhvm_progress_refresh](https://cloud.githubusercontent.com/assets/439401/5960450/b7b61c3a-a7d5-11e4-90cb-ea3b6e101fe3.png)

This message is a bad UX because clicking on this icon does nothing at all. Refreshing is done by clicking on the same icon way higher in the page.

**Comment by h4cc** [comment]
Oh, yes - good catch. Using the same CSS id.

Will fix that :+1:
