### ISSUE TITLE
Support the flat design for badges

### ISSUE THREAD

**Issue by stof** [h4cc/hhvm-progress#59]
Many tools have switch to flat badges by default. It would be great if your badges could be available this way too

**Comment by h4cc** [comment]
Thanks for this hint, added the missing badge styles.

The "badge popup" now offers changing style from plastic to flat and flat-square as well as using SVG or PNG graphics:
http://hhvm.h4cc.de/package/symfony/symfony

It is also mentioned on the "About" page:
http://hhvm.h4cc.de/about

:sunglasses:

**Comment by stof** [comment]
@h4cc fat-squared seems to return the wrong image on the about page (but the right one in the popup)

**Comment by h4cc** [comment]
Yep, that was a typo i made with "flat-squareD". Fixed now.
