### ISSUE TITLE
Update to support new HHVM versions on Travis?

### ISSUE THREAD

**Issue by ezzatron** [h4cc/hhvm-progress#61]
My HHVM status recently [dropped from "tested" to "partially tested"](http://hhvm.h4cc.de/package/eloquent/phony), which I thought was strange because I'm now testing with [more HHVM versions](https://travis-ci.org/eloquent/phony/builds/149090881) than I was [previously](https://travis-ci.org/eloquent/phony/builds/144883798).

Could it be that hhvm.h4cc.de doesn't yet understand the new HHVM versions (`hhvm-3.3`, `hhvm-3.6`, `hhvm-3.9`, `hhvm-3.12`, etc.) that [Travis now supports](https://docs.travis-ci.com/user/languages/php#HHVM-versions)?

**Comment by h4cc** [comment]
Thanks for that hint, will have a look on this.

By the way: hhvm.h4cc.de will discontinue. Successor is https://php-eye.com/
