### ISSUE TITLE
https://php-eye.com/ offline?

### ISSUE THREAD

**Issue by calebcartwright** [h4cc/hhvm-progress#64]
Hi there, hoping this is the right repository for https://php-eye.com/ (based on #62). 

The site appears to be down, which is resulting in us being unable to render badges for the service over at Shields.io (more details @ https://github.com/badges/shields/issues/3264).

Is https://php-eye.com/ still supported/running?

**Comment by h4cc** [comment]
Hi, its down and will stay down from my side. Thanks for asking. Regards.
